spring:
  datasource:
    url: jdbc:mysql://101.43.166.26:3306/bridge_dev?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: Lm5132735!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql